import mongoose from 'mongoose';
const Schema = mongoose.Schema;
var autoIncrement = require('mongoose-auto-increment');
var connection = mongoose.createConnection("mongodb://localhost/mcsm");
autoIncrement.initialize(connection);
//my beautiful database structure for the report sheet

var JssClass = new mongoose.Schema({
	pupil_id: String,
	staff_id: String,
	report_id: String,
	maths_name: {type: String, default: "Mathematics"},
	maths_test1:{type: Number, default: 0},
	maths_test2:{type: Number, default: 0},
	maths_test3:{type: Number, default: 0},
	maths_exam: {type: Number, default: 0},
	english_name: {type: String, default: "English"},
	english_test1:{type: Number, default: 0},
	english_test2:{type: Number, default: 0},
	english_test3:{type: Number, default: 0},
	english_exam: {type: Number, default: 0},
	yoruba_name: {type: String, default: "Yoruba"},
	yoruba_test1:{type: Number, default: 0},
	yoruba_test2:{type: Number, default: 0},
	yoruba_test3:{type: Number, default: 0},
	yoruba_exam: {type: Number, default: 0},
	basic_science: {type: String, default: "Basic Science"},
	basic_science_test1:{type: Number, default: 0},
	basic_science_test2:{type: Number, default: 0},
	basic_science_test3:{type: Number, default: 0},
	basic_science_exam: {type: Number, default: 0},
	social_name: {type: String, default: "Social Studies"},
	social_test1:{type: Number, default: 0},
	social_test2:{type: Number, default: 0},
	social_test3:{type: Number, default: 0},
	social_exam: {type: Number, default: 0},
	arts_name: {type: String, default: "Fine Arts"},
	arts_test1:{type: Number, default: 0},
	arts_test2:{type: Number, default: 0},
	arts_test3:{type: Number, default: 0},
	arts_exam: {type: Number, default: 0},
	agric_name: {type: String, default: "Agricultural Science"},
	agric_test1:{type: Number, default: 0},
	agric_test2:{type: Number, default: 0},
	agric_test3:{type: Number, default: 0},
	agric_exam: {type: Number, default: 0},
	civic_name: {type: String, default: "Civic Education"},
	civic_test1:{type: Number, default: 0},
	civic_test2:{type: Number, default: 0},
	civic_test3:{type: Number, default: 0},
	civic_exam: {type: Number, default: 0},
	crs_name: {type: String, default: "CRS"},
	crs_test1:{type: Number, default: 0},
	crs_test2:{type: Number, default: 0},
	crs_test3:{type: Number, default: 0},
	crs_exam: {type: Number, default: 0},
	phe_name: {type: String, default: "Physical Health Education"},
	phe_test1:{type: Number, default: 0},
	phe_test2:{type: Number, default: 0},
	phe_test3:{type: Number, default: 0},
	phe_exam: {type: Number, default: 0},
	business_name: {type: String, default: "Business Studies"},
	business_test1:{type: Number, default: 0},
	business_test2:{type: Number, default: 0},
	business_test3:{type: Number, default: 0},
	business_exam: {type: Number, default: 0},
	french_name: {type: String, default: "French"},
	french_test1:{type: Number, default: 0},
	french_test2:{type: Number, default: 0},
	french_test3:{type: Number, default: 0},
	french_exam: {type: Number, default: 0},
	computer_name: {type: String, default: "Computer Studies"},
	computer_test1:{type: Number, default: 0},
	computer_test2:{type: Number, default: 0},
	computer_test3:{type: Number, default: 0},
	computer_exam: {type: Number, default: 0},
	home_econs_name: {type: String, default: "Home Economics"},
	home_econs_test1:{type: Number, default: 0},
	home_econs_test2:{type: Number, default: 0},
	home_econs_test3:{type: Number, default: 0},
	home_econs_exam: {type: Number, default: 0},
	music_name: {type: String, default: "Music"},
	music_test1:{type: Number, default: 0},
	music_test2:{type: Number, default: 0},
	musci_test3:{type: Number, default: 0},
	music_exam: {type: Number, default: 0},
	basic_tech_name: {type: String, default: "Basic Technology"},
	basic_tech_test1:{type: Number, default: 0},
	basic_tech_test2:{type: Number, default: 0},
	basic_tech_test3:{type: Number, default: 0},
	basic_tech_exam: {type: Number, default: 0},
	irk_name: {type: String, default: "IRK"},
	irk_test1:{type: Number, default: 0},
	irk_test2:{type: Number, default: 0},
	irk_test3:{type: Number, default: 0},
	irk_exam: {type: Number, default: 0},
	


},
{
    timestamps: true//this will automatically add the createdAt and the updatedAt field for us
});

// School.plugin(autoIncrement.plugin, { model: 'School', field: 'school_id' });
module.exports = mongoose.model('JssClass', JssClass);
